const category = [
    { cat: '3D Renders' },
    { cat: 'Arts & Culture' },
    { cat: 'Animals' },
    { cat: 'Architecture & Interiors' },
    { cat: 'Business & Work' },
    { cat: 'Current Events' },
    { cat: 'Editorial' },
    { cat: 'Experimental' },
    { cat: 'Featured Monochromatic' },
    { cat: 'Fashion & Beauty' },
    { cat: 'Food & Drink' },
    { cat: 'Film' },
    { cat: 'Health & Wellness' },
    { cat: 'Nature' },
    { cat: 'People' },
    { cat: 'Sports' },
    { cat: 'Spirituality' },
    { cat: 'Street Photography' },
    { cat: 'Solid' },
    { cat: 'Tatto' },
    { cat: 'Textures & Patterns' },
    { cat: 'Travel' },
    { cat: 'Wallpapers' },
]
export default category;